#!/bin/bash
# imos is a utility library for BASH.

IMOSH_VERSION='2014-09-29 03:32:43 +0900 (0acb86f)'

# Enables error checking if imosh is called in a script.
if ! shopt login_shell >/dev/null; then
  # Make a script fail when
  # - a command returns non-zero value (-e).
  # - an undefined variable is referred (-u).
  set -e -u
  # Return if imosh is reloaded.
  if [ "${__IMOSH_IS_LOADED+loaded}" = 'loaded' ]; then
    return
  fi
fi

# func::addslashes -- Quotes a string with backslahses.
#
# Usage:
#   void func::addslashes(string* subject)
#
# Quotes string with backslashes. Single quote, double quote and backslash in
# subject are escaped.
func::addslashes() {
  func::str_replace "${1}" '\' '\\'
  func::str_replace "${1}" "'" "\\'"
  func::str_replace "${1}" '"' '\"'
}

# func::array_unique -- Remove duplicated elements from an array variable.
#
# Usage:
#   void func::array_unique(string[]* variable)
func::array_unique() {
  local __array_unique_variable="${1}"
  if eval "[ \"\${#${__array_unique_variable}[*]}\" -eq 0 ]"; then
    return
  fi
  eval "local __array_unique_values=(\"\${${__array_unique_variable}[@]}\")"
  func::sort __array_unique_values
  local __array_unique_i=0
  local __array_unique_size="${#__array_unique_values[*]}"
  local __array_unique_result=("${__array_unique_values[0]}")
  while (( __array_unique_i += 1, __array_unique_i < __array_unique_size )); do
    if [ "${__array_unique_values[$(( __array_unique_i - 1 ))]}" != \
         "${__array_unique_values[${__array_unique_i}]}" ]; then
      __array_unique_result+=("${__array_unique_values[${__array_unique_i}]}")
    fi
  done
  eval "${__array_unique_variable}=(\"\${__array_unique_result[@]}\")"
}

# func::atexit -- Registers a function on shutdown.
#
# Usage:
#   void func::atexit(string command)
func::atexit() {
  if [ "$#" -eq 1 ]; then
    echo "$1" >>"${__IMOSH_CORE_TMPDIR}/atexit.sh"
  else
    LOG ERROR "Wrong number of arguments: $#"
    return 1
  fi
}

# func::bin2hex -- Converts a binary string into hexadecimal representation.
#
# Usage:
#   void func::bin2hex(string* hexadecimal_output, string binary_input)
#   void func::bin2hex(string binary_input) > hexadecimal_output
#   void func::bin2hex() < binary_input > hexadecimal_output
#
# Converts binary data into hexadecimal representation.
func::bin2hex() {
  if [ "$#" -eq 0 ]; then
    od -An -tx1 | tr -d ' \n'
    return
  elif [ "$#" -eq 1 ]; then
    func::bin2hex <<<"$1"
    return
  elif [ "$#" -ne 2 ]; then
    LOG FATAL "func::bin2hex requires two arguments, but $# arguments."
    return 1
  fi
  local __bin2hex_destination="$1"
  local __bin2hex_data="$2"

  eval "${__bin2hex_destination}=\"\$(func::print \"${__bin2hex_data}\" | func::bin2hex)\""
}

# func::boolval -- Casts a variable as a boolean value.
#
# Usage:
#   bool func::boolval(string* variable)
#
# Casts variable as a boolean value.  If it fails, returns 1.
func::boolval() {
  local __boolval_variable="$1"
  eval "local __boolval_value=\"\${${__boolval_variable}}\""

  func::trim __boolval_value
  if [ "${__boolval_value}" = '' ]; then
    __boolval_value=0
  elif [[ "${__boolval_value}" =~ ^T|t|[Tt]rue$ ]]; then
    __boolval_value=1
  elif [[ "${__boolval_value}" =~ ^F|f|[Ff]alse$ ]]; then
    __boolval_value=0
  elif func::intval __boolval_value; then
    if (( __boolval_value )); then
      __boolval_value=1
    fi
  else
    func::let "${__boolval_variable}" 0
    return 1
  fi
  func::let "${__boolval_variable}" "${__boolval_value}"
}

# func::cast -- Casts a variable.
#
# Usage:
#   bool func::cast(variant* variable, string type)
#
# Casts variable into a specified type.
func::cast() {
  local __cast_variable="$1"
  local __cast_type="$2"

  case "${__cast_type}" in
    int)     if ! func::intval "${__cast_variable}"; then return 1; fi;;
    float)   if ! func::floatval "${__cast_variable}"; then return 1; fi;;
    string)  if ! func::strval "${__cast_variable}"; then return 1; fi;;
    bool)    if ! func::boolval "${__cast_variable}"; then return 1; fi;;
    variant) return 0;;
    *)       LOG FATAL "Unknown type: ${__cast_type}";;
  esac
}

# func::escapeshellarg - Escapes a variable as a shell argument.
#
# Usage:
#   void func::escapeshellarg(string* variable)
#
# Escapes variable's content.
func::escapeshellarg() {
  local __escapeshellarg_variable="$1"
  local __escapeshellarg_search="'"
  local __escapeshellarg_replace="'\\''"

  eval "${__escapeshellarg_variable}=\"'\${${__escapeshellarg_variable}//\${__escapeshellarg_search}/\${__escapeshellarg_replace}}'\""
}

# func::exit, func::die
#
# Usage:
#   // 1. Message form.
#   void func::exit(string message)
#   // 2. Status form.
#   void func::exit(int status = 0)
#   // 1. Message form.
#   void func::die(string message)
#   // 2. Status form
#   void func::die(int status = 0)
#
# func::exit kills all the subprocesses of the current program.  If an integer
# argument is given, func::exit exists with the status.  Otherwise, func::exit
# shows the given message and exits with status 0.
#
# func::die shows a stack trace and delegates arguments to func::exit.
func::exit() {
  if [ "$#" -eq 0 ]; then
    set -- 0
  fi
  if [ "$#" -le 1 ]; then
    local status=0
    if [[ "$1" =~ ^[0-9]+$ ]]; then
      status="$1"
    else
      local message="$1"
      func::rtrim message
      func::println "${message}"
    fi
    imosh::exit "${status}"
  else
    LOG FATAL "Wrong number of arumnets: $#"
  fi
}

func::die() {
  if [ "$#" -le 1 ]; then
    imosh::stack_trace "*** imosh::die stack trace: ***"
    func::exit "$@"
  else
    LOG ERROR "Wrong number of arguments: $#"
  fi
}

# func::explode -- Splits a string by a substring.
#
# Usage:
#   void func::explode(string* variable, string delimiter, string value)
#
# Splits a string by string.
func::explode() {
  local __explode_variable="${1}"
  local __explode_delimiter="${2}"
  local __explode_value="${3}"
  local __explode_result=()

  func::str_replace __explode_value "${__explode_delimiter}" $'\x02'
  while IFS='' read -r -d $'\x02' __explode_term; do
    __explode_result+=("${__explode_term}")
  done <<<"${__explode_value}"$'\x02'
  eval "${__explode_variable}=(\"\${__explode_result[@]}\")"
}

# func::floatval -- Casts a variable as a float value.
#
# Usage:
#   bool func::floatval(string* variable)
#
# Casts variable into float type.  If it fails, returns 1.
func::floatval() {
  local __floatval_variable="$1"

  local __floatval_value
  eval "__floatval_value=\"\${${__floatval_variable}}\""
  if [[ "${__floatval_value}" =~ ^[[:space:]]*(-?[0-9]+(\.[0-9]+)?) ]]; then
    func::let "${__floatval_variable}" "${BASH_REMATCH[1]}"
  else
    return 1
  fi
}

# func::getchildpids -- Gets child process IDs.
#
# Usage:
#   func::getchildpids(int[]* variable)
func::getchildpids() {
  local __getchildpids_variable="$1"
  local __getchildpids_mypid=''
  func::getmypid __getchildpids_mypid
  local __getchildpids_pid='' __getchildpids_ppid=''
  local __getchildpids_result=()
  while IFS=$' \t\n' read -r -d $'\n' __getchildpids_ppid __getchildpids_pid; do
    if [ "${__getchildpids_ppid}" = "${__getchildpids_mypid}" ]; then
      __getchildpids_result+=("${__getchildpids_pid}")
    fi
  done <<<"$(ps -o ppid,pid)"
  if [ "${#__getchildpids_result[*]}" -eq 0 ]; then
    eval "${__getchildpids_variable}=()"
  else
    eval "${__getchildpids_variable}=(\"\${__getchildpids_result[@]}\")"
  fi
}

# func::getmypid -- Gets the current process ID.
#
# Usage:
#   func::pid(int* variable)
func::getmypid() {
  local __getmypid_variable="$1"
  if func::isset BASHPID; then
    func::let "${__getmypid_variable}" "${BASHPID}"
  else
    local __getmypid_pid_file="$(mktemp "${__IMOSH_CORE_TMPDIR}/pid.XXXXXX")"
    "${SHELL}" -c 'echo "${PPID}"' >"${__getmypid_pid_file}"
    read "${__getmypid_variable}" <"${__getmypid_pid_file}"
  fi
}

# func::greg_match -- Checks if a string matches a GREG pattern.
#
# Usage:
#   void func::greg_match(string pattern, string subject)
#
# Replace pattern with replace in *subject.
func::greg_match() {
  if ! shopt extglob >/dev/null; then
    shopt -s extglob
    func::greg_match "$@"
    local result="$?"
    shopt -u extglob
    return "${result}"
  fi

  if [ "$#" -ne 2 ]; then
    LOG FATAL 'func::greg_match takes exactly 2 arguments.'
  fi
  local __greg_match_pattern="${1}"
  local __greg_match_subject="${2}"

  if [[ "${__greg_match_subject}" = ${__greg_match_pattern} ]]; then
    return 0
  else
    return 1
  fi
}

# func::greg_replace -- Replace a GREG pattern with a string.
#
# Usage:
#   void func::greg_replace(string* subject, string pattern, string replace)
#
# Replace pattern with replace in *subject.
func::greg_replace() {
  if ! shopt extglob >/dev/null; then
    shopt -s extglob
    func::greg_replace "$@"
    shopt -u extglob
    return "$?"
  fi

  if [ "$#" -ne 3 ]; then
    LOG FATAL 'func::greg_replace takes exactly 3 arguments.'
  fi
  local __greg_replace_subject_variable="${1}"
  local __greg_replace_search="${2}"
  local __greg_replace_replace="${3}"

  eval "${__greg_replace_subject_variable}=\"\${${__greg_replace_subject_variable}//\${__greg_replace_search}/\${__greg_replace_replace}}\""
}

# func::hex2bin -- Decodes a hexadecimally encoded binary string.
#
# Usage:
#   void func::hex2bin(string* output, string input)
#   void func::hex2bin(string* variable)
#   void func::hex2bin() < input > output
#
# Decodes a hexadecimally encoded binary string.
func::hex2bin() {
  if [ "$#" -eq 0 ]; then
    local __hex2bin_variable=''
    __func::hex2bin
  elif [ "$#" -eq 2 ]; then
    local __hex2bin_variable="$1" __hex2bin_data="$2" __hex2bin_result=''
    __func::hex2bin <<<"${__hex2bin_data}"
    func::let "${__hex2bin_variable}" "${__hex2bin_result}"
  elif [ "$#" -eq 1 ]; then
    local __hex2bin_variable="$1" __hex2bin_result=''
    eval "func::hex2bin \"\${__hex2bin_variable}\" \"\${${__hex2bin_variable}}\""
  fi
}

__func::hex2bin() {
  local __hex2bin_char='' __hex2bin_buffer=''
  while read -n 1 __hex2bin_char; do
    case "${__hex2bin_char}" in
      [0-9a-fA-F]) __hex2bin_buffer+="${__hex2bin_char}";;
      *) continue;;
    esac
    if [ "${#__hex2bin_buffer}" -eq 2 ]; then
      if [ "${__hex2bin_variable}" = '' ]; then
        printf "\\x${__hex2bin_buffer}"
      else
        eval "__hex2bin_result+=\$'\\x${__hex2bin_buffer}'"
      fi
      __hex2bin_buffer=''
    fi
  done
}

# func::implode -- Joins array elements with a string.
#
# Usage:
#   // 1. Function form.
#   void func::implode(string* variable, string glue, string[]* pieces)
#   // 2. Command form.
#   void func::implode(string glue, string[]* pieces) > result
#   // 3. Stream form.
#   void func::implode(string glue) < input > output
#
# func::implode joins `pieces` with `glue`.
# *Stream form* uses the IFS environment variable as an input separator and
# processes line by line.
#
# ### Alias
# func::join is an alias of func::implode.
func::implode() {
  # 1. Function form.
  if [ "$#" -eq 3 ]; then
    local __implode_variable="${1}"
    local __implode_glue="${2}"
    local __implode_pieces=()
    eval "local __implode_pieces=(\"\${${3}[@]}\")"

    local __implode_size="${#__implode_pieces[@]}"
    local __implode_i=0
    local __implode_result=''
    while (( __implode_i < __implode_size )); do
      if (( __implode_i != 0 )); then
        __implode_result+="${__implode_glue}"
      fi
      __implode_result+="${__implode_pieces[${__implode_i}]}"
      (( __implode_i += 1 )) || true
    done
    func::let "${__implode_variable}" "${__implode_result}"
  # 2. Command form
  elif [ "$#" -eq 2 ]; then
    local __implode_output=''
    # 1. Function form.
    func::implode __implode_output "$1" "$2"
    func::println "${__implode_output}"
    return
  # 3. Stream form.
  elif [ "$#" -eq 1 ]; then
    local __implode_line=''
    while read -r __implode_line; do
      local pieces=(${__implode_line})
      # 2. Command form.
      func::implode "$1" pieces
    done
    return
  # Argument mismatch.
  else
    LOG ERROR "The number of arguments does not match func::implode: $#"
    return 1
  fi
}

func::join() { func::implode "$@"; }

# func::intval -- Casts a variable as an integer value.
#
# Usage:
#   bool func::intval(string* variable)
#
# Casts variable into integer type.  If it fails, returns 1.
func::intval() {
  local __intval_variable="$1"

  local __intval_value
  eval "__intval_value=\"\${${__intval_variable}}\""
  if [[ "${__intval_value}" =~ ^[[:space:]]*(-?[0-9]+) ]]; then
    func::let "${__intval_variable}" "${BASH_REMATCH[1]}"
  else
    return 1
  fi
}

# func::isset -- Checks if a variable exists.
#
# Usage:
#   bool func::isset(variant* variable)
#
# Returns true iff variable exists.
#
# CAVEATS: func::isset returns true for uninitialized variables in BASH 3, and
#          returns false for them in BASH 4.
func::isset() {
  local __isset_variable="$1"

  eval "local __isset_state=\"\${${__isset_variable}+set}\""
  if [ "${__isset_state}" = 'set' ]; then
    return 0
  fi
  return 1
}

# func::let -- Assigns a value into a variable.
#
# Usage:
#   func::let(string* destination, string value)
#
# Assigns value into *destination.
func::let() {
  local __let_destination="$1"
  local __let_value="$2"

  eval "${__let_destination}=\"\${__let_value}\""
}

# func::ltrim -- Strips whitespace(s) from the beginning of a string.
#
# Usage:
#   void func::ltrim(string* variable)
#
# Strips whitespace (or other characters) from the beginning of a string.
func::ltrim() {
  local __ltrim_variable="$1"

  eval "${__ltrim_variable}=\"\${${__ltrim_variable}#\"\${${__ltrim_variable}%%[![:space:]]*}\"}\""
}

# func::md5 -- Calculates a MD5 hash.
#
# Usage:
#   void func::md5() < input > hash
#   void func::md5(string data) > hash
#   void func::md5(string* variable, string data)
func::md5() {
  if [ "$#" -eq 0 ]; then
    openssl md5 -binary | func::bin2hex
  elif [ "$#" -eq 1 ]; then
    func::print "${1}" | func::md5
  elif [ "$#" -eq 2 ]; then
    local __md5_variable="$1"
    local __md5_data="$2"
    eval "${__md5_variable}=\"\$(func::md5 \"\${__md5_data}\")\""
  fi
}

# func::ord -- Gets a character's ASCII code.
#
# Usage:
#   func::ord(string* variable, string character)
#
# Sets ASCII value of character to variable.
func::ord() {
  local __ord_variable="$1"
  local __ord_character="$2"
  local __ord_result="$(printf '%d' \'"${__ord_character}")"
  eval "${__ord_variable}=\"\${__ord_result}\""
}

# func::print -- Prints a message.
#
# Usage:
#   void func::print(string message...) > output
#
# Print message to the standard output.  While "echo" consumes flags,
# func::print does not consume any flags, so this is theoretically safe.
func::print() {
  printf "%s" "$*"
}

# func::println -- Prints a message with a new line.
#
# Usage:
#   void func::println(string message...) > output
#
# Print message to the standard output with a new line.  While "echo" consumes
# flags, func::println does not consume any flags, so this is theoretically
# safe.
func::println() {
  printf "%s\n" "$*"
}

# func::rand -- Generates a random integer.
#
# Usage:
#   void func::rand(int* variable)
#   void func::rand(int* variable, int minimum, int maximum)
#
# Generates a random integer.
func::rand() {
  if [ "$#" -eq 1 ]; then
    func::rand "$1" 0 2147483647
    return
  fi
  if [ "$#" -ne 3 ]; then
    LOG FATAL 'func::rand requires one or three arguments.'
  fi

  local __rand_variable="$1"
  local __rand_minimum="$2"
  local __rand_maximum="$3"
  local __rand_range=0 __rand_value=0
  if (( __rand_minimum > __rand_maximum )); then
    LOG FATAL "minimum must be larger than maximum:" \
              "minimum=${__rand_minimum}, maximum=${__rand_maximum}"
  fi
  (( __rand_value = RANDOM ^ (RANDOM << 8) ^
                    (RANDOM << 16) ^ (RANDOM << 24) ^
                    (RANDOM << 32) ^ (RANDOM << 40) ^
                    (RANDOM << 48) ^ (RANDOM << 56),
     __rand_range = __rand_maximum - __rand_minimum + 1,
     __rand_value = __rand_minimum +
         ( __rand_value % __rand_range + __rand_range ) % __rand_range,
     1 ))
  func::let "${__rand_variable}" "${__rand_value}"
}

# func::rtrim -- Strips whitespace(s) from the end of a string.
#
# Usage:
#   void func::rtrim(string* variable)
#
# Strips whitespace (or other characters) from the end of a string.
func::rtrim() {
  local __rtrim_variable="$1"

  eval "${__rtrim_variable}=\"\${${__rtrim_variable}%\"\${${__rtrim_variable}##*[![:space:]]}\"}\""
}

# func::sort -- Sorts a string-array variable.
#
# Usage:
#   void func::sort(string[]* variable)
func::sort() {
  local __sort_name="${1}"
  eval "local __sort_size=\"\${#${__sort_name}[*]}\""
  if [ "${__sort_size}" -lt 2 ]; then
    return
  fi
  eval "local __sort_values=(\"\${${__sort_name}[@]}\")"
  __func::quick_sort
  eval "${__sort_name}=(\"\${__sort_values[@]}\")"
}

__func::quick_sort() {
  local size="${#__sort_values[@]}"
  local pivot="${__sort_values[$(( size / 2 ))]}"
  local values1=() values2=() values3=()

  for value in "${__sort_values[@]}"; do
    if [ "${value}" \< "${pivot}" ]; then
      values1+=("${value}")
    elif [ "${value}" \> "${pivot}" ]; then
      values3+=("${value}")
    else
      values2+=("${value}")
    fi
  done
  func::sort values1
  func::sort values3
  __sort_values=()
  if [ "${#values1[*]}" -ne 0 ]; then
    __sort_values+=("${values1[@]}")
  fi
  if [ "${#values2[*]}" -ne 0 ]; then
    __sort_values+=("${values2[@]}")
  fi
  if [ "${#values3[*]}" -ne 0 ]; then
    __sort_values+=("${values3[@]}")
  fi
}

# func::str_replace -- Replaces a substring with another substring.
#
# Usage:
#   void func::str_replace(string* subject, string search, string replace)
#
# Replace search with replace in *subject.
func::str_replace() {
  if [ "$#" -ne 3 ]; then
    LOG FATAL 'func::str_replace takes exactly 3 arguments.'
  fi
  local __str_replace_subject_variable="${1}"
  local __str_replace_search="${2}"
  local __str_replace_replace="${3}"

  eval "${__str_replace_subject_variable}=\"\${${__str_replace_subject_variable}//\"\${__str_replace_search}\"/\${__str_replace_replace}}\""
}

# func::strcpy -- Copies a string from a variable to another variable.
#
# Usage:
#   void func::strcpy(string* destination, string *source)
#
# Assigns the content of a variable specified as source into destination.
func::strcpy() {
  local __strcpy_destination="$1"
  local __strcpy_source="$2"

  eval "${__strcpy_destination}=\"\${${__strcpy_source}}\""
}

# func::strtolower -- Makes a string lowercase.
#
# Usage:
#   void func::strtolower(string* variable)
#   void func::strtolower() < input > output
#
# Makes variable lowercase.
func::strtolower() {
  if [ "$#" -eq 0 ]; then
    tr '[A-Z]' '[a-z]'
    return
  fi
  local __strtolower_variable="$1"
  eval "local __strtolower_value=\"\${${__strtolower_variable}}\""
  # This is faster than tr for short strings.
  # TODO(imos): Use ${variable,,} instead once Mac OSX supports BASH 4.
  __strtolower_value="${__strtolower_value//A/a}"
  __strtolower_value="${__strtolower_value//B/b}"
  __strtolower_value="${__strtolower_value//C/c}"
  __strtolower_value="${__strtolower_value//D/d}"
  __strtolower_value="${__strtolower_value//E/e}"
  __strtolower_value="${__strtolower_value//F/f}"
  __strtolower_value="${__strtolower_value//G/g}"
  __strtolower_value="${__strtolower_value//H/h}"
  __strtolower_value="${__strtolower_value//I/i}"
  __strtolower_value="${__strtolower_value//J/j}"
  __strtolower_value="${__strtolower_value//K/k}"
  __strtolower_value="${__strtolower_value//L/l}"
  __strtolower_value="${__strtolower_value//M/m}"
  __strtolower_value="${__strtolower_value//N/n}"
  __strtolower_value="${__strtolower_value//O/o}"
  __strtolower_value="${__strtolower_value//P/p}"
  __strtolower_value="${__strtolower_value//Q/q}"
  __strtolower_value="${__strtolower_value//R/r}"
  __strtolower_value="${__strtolower_value//S/s}"
  __strtolower_value="${__strtolower_value//T/t}"
  __strtolower_value="${__strtolower_value//U/u}"
  __strtolower_value="${__strtolower_value//V/v}"
  __strtolower_value="${__strtolower_value//W/w}"
  __strtolower_value="${__strtolower_value//X/x}"
  __strtolower_value="${__strtolower_value//Y/y}"
  __strtolower_value="${__strtolower_value//Z/z}"
  eval "${__strtolower_variable}=\"\${__strtolower_value}\""
}

# func::strtoupper -- Makes a string uppercase.
#
# Usage:
#   void func::strtoupper(string* variable)
#   void func::strtoupper() < input > output
#
# Makes variable uppercase.
func::strtoupper() {
  if [ "$#" -eq 0 ]; then
    tr '[a-z]' '[A-Z]'
    return
  fi
  local __strtoupper_variable="$1"
  eval "local __strtoupper_value=\"\${${__strtoupper_variable}}\""
  # This is faster than tr for short strings.
  # TODO(imos): Use ${variable^^} instead once Mac OSX supports BASH 4.
  __strtoupper_value="${__strtoupper_value//a/A}"
  __strtoupper_value="${__strtoupper_value//b/B}"
  __strtoupper_value="${__strtoupper_value//c/C}"
  __strtoupper_value="${__strtoupper_value//d/D}"
  __strtoupper_value="${__strtoupper_value//e/E}"
  __strtoupper_value="${__strtoupper_value//f/F}"
  __strtoupper_value="${__strtoupper_value//g/G}"
  __strtoupper_value="${__strtoupper_value//h/H}"
  __strtoupper_value="${__strtoupper_value//i/I}"
  __strtoupper_value="${__strtoupper_value//j/J}"
  __strtoupper_value="${__strtoupper_value//k/K}"
  __strtoupper_value="${__strtoupper_value//l/L}"
  __strtoupper_value="${__strtoupper_value//m/M}"
  __strtoupper_value="${__strtoupper_value//n/N}"
  __strtoupper_value="${__strtoupper_value//o/O}"
  __strtoupper_value="${__strtoupper_value//p/P}"
  __strtoupper_value="${__strtoupper_value//q/Q}"
  __strtoupper_value="${__strtoupper_value//r/R}"
  __strtoupper_value="${__strtoupper_value//s/S}"
  __strtoupper_value="${__strtoupper_value//t/T}"
  __strtoupper_value="${__strtoupper_value//u/U}"
  __strtoupper_value="${__strtoupper_value//v/V}"
  __strtoupper_value="${__strtoupper_value//w/W}"
  __strtoupper_value="${__strtoupper_value//x/X}"
  __strtoupper_value="${__strtoupper_value//y/Y}"
  __strtoupper_value="${__strtoupper_value//z/Z}"
  eval "${__strtoupper_variable}=\"\${__strtoupper_value}\""
}

# func::strval -- Casts a variable as a string value.
#
# Usage:
#   void func::strval(string* variable)
#
# Casts variable into string type.
func::strval() {
  local __strval_variable="$1"

  eval "${__strval_variable}=\"\${${__strval_variable}}\""
}

# func::throttle -- Throttles by the number of child processes.
#
# Usage:
#   func::throttle(int limit)
func::throttle() {
  local __throttle_limit="$1"
  local __throttle_pids=()
  local __throttle_sleep=0

  while :; do
    func::getchildpids __throttle_pids
    if [ "${#__throttle_pids[*]}" -lt "${__throttle_limit}" ]; then
      break
    fi
    if (( __throttle_sleep += 1, __throttle_sleep < 10 )); then
      sleep "0.${__throttle_sleep}"
    else
      sleep 1
    fi
  done
}

# func::tmpfile -- Creates a temporary file.
#
# Usage:
#   // 1. Function form.
#   void func::tmpfile(string* path)
#   // 2. Command form.
#   void func::tmpfile() > path
#
# Creates a temporary file with a unique name under TMPDIR.
func::tmpfile() {
  # 1. Function form.
  if [ "$#" -eq 1 ]; then
    local __tmpfile_variable="$1"
    func::let "${__tmpfile_variable}" \
        "${TMPDIR}/tmpfile.${RANDOM}.${RANDOM}.${RANDOM}.${RANDOM}.${RANDOM}"
  # 2. Command form.
  elif [ "$#" -eq 0 ]; then
    local tmpfile=''
    # 1. Function form.
    func::tmpfile tmpfile
    func::println "${tmpfile}"
  # Argument mismatch.
  else
    LOG ERROR "The number of arguments does not match func::tmpfile: $#"
    return 1
  fi
}

# func::trim -- Strips whitespaces from both sides.
#
# Usage:
#   void func::trim(string* variable)
#
# Strips whitespace (or other characters) from the beginning and end of a
# string.
func::trim() {
  func::rtrim "$1"
  func::ltrim "$1"
}

CHECK() {
  if ! "$@"; then
    IFS=' ' eval 'imosh::stack_trace "*** Check failure: $* ***"'
  fi
}

imosh::internal::loglevel() {
  case "$1" in
    ALL)     echo 0;;
    INFO)    echo 1;;
    WARNING) echo 2;;
    ERROR)   echo 3;;
    FATAL)   echo 4;;
    NONE)    echo 5;;
    *)       LOG FATAL "unknown level: $1";;
  esac
}

LOG() {
  local level="$1"
  shift

  case "${level}" in
    INFO|WARNING|ERROR|FATAL) :;;
    *) LOG FATAL "no such log level: ${level}"
  esac
  local datetime="$(date +'%m%d %T.%N')"
  # For systems not supporting %N in date.
  datetime="${datetime/.N/.000000}"
  datetime="${datetime:0:20}"
  local pid
  if func::isset __IMOSH_LOG_PID; then
    pid="${__IMOSH_LOG_PID}"
  else
    func::getmypid pid
  fi
  local file="${BASH_SOURCE[1]##*/}"
  if [ "${file}" = '' ]; then file='-'; fi
  local message=(
      "${level:0:1}${datetime}"
      "${pid}"
      "${file}:${BASH_LINENO[0]}]"
      "$@")
  message="$(echo "${message[@]}")"
  if [ "$(imosh::internal::loglevel "${level}")" -ge \
       "$(imosh::internal::loglevel "${FLAGS_stacktrace_threshold}")" ]; then
    message+=$'\n'
    message+="$(imosh::stack_trace "*** LOG ${level} stack trace: ***" 2>&1)"
  fi
  local logtostderr=0
  if func::isset FLAGS_logtostderr; then
    logtostderr="${FLAGS_logtostderr}"
  fi
  local alsologtostderr=0
  if func::isset FLAGS_alsologtostderr; then
    alsologtostderr="${FLAGS_alsologtostderr}"
  fi
  case "${level}" in
    INFO)
      if (( logtostderr || alsologtostderr )); then
        echo "${message}" >&2
      fi
      if (( ! logtostderr )); then
        echo "${message}" >&101
      fi
      ;;
    WARNING)
      if (( logtostderr || alsologtostderr )); then
        echo "${message}" >&2
      fi
      if (( ! logtostderr )); then
        echo "${message}" >&101
        echo "${message}" >&102
      fi
      ;;
    ERROR)
      echo "${message}" >&2
      if (( ! logtostderr )); then
        echo "${message}" >&101
        echo "${message}" >&102
        echo "${message}" >&103
      fi
      ;;
    FATAL)
      echo "${message}" >&2
      if (( ! logtostderr )); then
        echo "${message}" >&101
        echo "${message}" >&102
        echo "${message}" >&103
        echo "${message}" >&104
      fi
      imosh::quiet_die 1
      ;;
  esac
}

imosh::internal::log_file() {
  local severity="${1}"
  local path=''
  if [ "${FLAGS_log_dir}" == '' ]; then
    return
  fi
  path+="${FLAGS_log_dir}/"
  path+="${__IMOSH_LOG_PREFIX}.${severity}.${__IMOSH_LOG_SUFFIX}"
  func::print "${path}"
}

imosh::internal::init_log() {
  # Close descriptors for logs beforehand for BASH3's bug.
  exec 101>&- 102>&- 103>&- 104>&-
  if [ "${FLAGS_log_dir}" != '' -a -w "${FLAGS_log_dir}" ]; then
    exec 101>"$(imosh::internal::log_file INFO)"
    exec 102>"$(imosh::internal::log_file WARNING)"
    exec 103>"$(imosh::internal::log_file ERROR)"
    exec 104>"$(imosh::internal::log_file FATAL)"
    return
  fi
  exec 101>/dev/null 102>/dev/null 103>/dev/null 104>/dev/null
  if [ "${FLAGS_log_dir}" == '' ]; then
    return
  fi
  LOG ERROR "failed to open files to write logs: ${__IMOSH_LOG_DIR}"
}

# Parses arguments without getopt.
imosh::internal::parse_args() {
  local class_name="$1"; shift

  local upper_class_name="${class_name}"
  func::strtoupper upper_class_name
  local arg arg_name arg_value
  IMOSH_ARGV=()
  IMOSH_ARGS=()
  while [ "$#" != '0' ]; do
    local arg="$1"
    shift
    if [ "${arg:0:1}" != '-' ]; then
      IMOSH_ARGV+=("${arg}")
      continue
    fi
    if [[ "${arg}" =~ ^-[0-9] ]]; then
      IMOSH_ARGV+=("${arg}")
      continue
    fi
    if [ "${arg}" = '--' ]; then
      IMOSH_ARGV+=("$@")
      break
    fi
    case "${arg}" in
      --*) arg="${arg:2}";;
      -*) arg="${arg:1}";;
    esac
    arg_name="${arg%%=*}"
    if [[ ! "${arg_name}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
      LOG FATAL "${class_name} name is bad: ${arg_name}"
    fi
    arg_value="${arg:${#arg_name}}"
    if [ "${arg_value:0:1}" != '=' ]; then
      if [ "${arg_name:0:2}" = 'no' ]; then
        if func::isset "${upper_class_name}S_${arg_name:2}"; then
          if [ "${class_name}" != 'flag' ] || \
             [ "$(imosh::internal::flag_type "${arg_name:2}")" = 'bool' ]; then
            IMOSH_ARGS+=("${upper_class_name}S_${arg_name:2}=0")
            continue
          fi
        fi
      fi
      if func::isset "${upper_class_name}S_${arg_name}"; then
        if [ "${class_name}" != 'flag' ] ||
           [ "$(imosh::internal::flag_type "${arg_name}")" = 'bool' ]; then
          IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=1")
          continue
        fi
      fi
      if ! func::isset "${upper_class_name}S_${arg_name}"; then
        LOG FATAL "no such bool ${class_name} is defined:" \
                  "(${upper_class_name}S_)${arg_name}"
      fi
      if [ "$#" -eq 0 ]; then
        LOG FATAL "the ${arg_name} flag requires a value"
      fi
      arg_value="=${1}"
      shift
    fi
    arg_value="${arg_value:1}"
    if func::isset "${upper_class_name}S_${arg_name}"; then
      if [ "${class_name}" = 'flag' ]; then
        if ! imosh::internal::convert_type \
               "$(imosh::internal::flag_type "${arg_name}")" \
               "${arg_value}" >/dev/null; then
          LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value}"
        else
          arg_value="$(imosh::internal::convert_type \
                             "$(imosh::internal::flag_type "${arg_name}")" \
                             "${arg_value}")"
        fi
      fi
      IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value}")
      continue
    fi
    LOG FATAL "no such ${class_name} is defined:" \
              "(${upper_class_name}S_)${arg_name}"
  done
}

# imosh::exit
#
# Usage:
#   void imosh::exit(int status = 0)
#
# imosh::exit kills all the subprocesses of the root process with the status.
imosh::exit() {
  if [ "$#" -eq 0 ]; then
    set -- 0
  fi
  if [ "$#" -eq 1 ]; then
    local status="$1"
    echo "${status}" >"${__IMOSH_CORE_TMPDIR}/status"

    local PID=''
    func::getmypid PID
    # First, kill all the childs of the current process so that no child
    # processes spawn new processes.
    __imosh::kill "${PID}"
    # Then, try to kill other processes under the root process except this
    # process.
    __imosh::kill "${IMOSH_ROOT_PID}"
    # Send a TERM signal to the root process.
    kill -TERM "${IMOSH_ROOT_PID}" 2>/dev/null || true
    # Exit immediately.
    exit "${status}"
  else
    LOG FATAL "Wrong number of aruments: $#"
  fi
}

# __imosh::kill
#
# Usage:
#   void __imosh::kill(int pid)
#
# __imosh::kill must not be called by functions other than imosh::exit because
# a killer process `PID` must not be stopped by a signal.
__imosh::kill() {
  if [ "$#" -eq 1 ]; then
    local target_pid="$1"
    LOG INFO "killing ${target_pid}..."
    local keep_alive=0
    if [ "${target_pid}" = "${PID}" -o \
         "${target_pid}" = "${IMOSH_ROOT_PID}" ]; then
      keep_alive=1
    fi
    if (( ! keep_alive )); then
      kill -STOP "${target_pid}" 2>/dev/null || true
    fi
    export IFS=$' \t\n'
    local child_pids="$(ps -o ppid,pid | \
                        grep "^[[:space:]]*${target_pid}[[:space:]]" | \
                        awk '{ print $2 }')"
    if [ "${child_pids}" != '' ]; then
      LOG INFO "Target PID (${target_pid})'s child PIDs are: ${child_pids[*]}"
      local child=''
      for child in ${child_pids}; do
        __imosh::kill "${child}"
      done
    else
      LOG INFO "Target PID (${target_pid}) has no child PIDs."
    fi
    if (( ! keep_alive )); then
      kill -KILL "${target_pid}" 2>/dev/null || true
    fi
  else
    LOG FATAL "Wrong number of arguments: $#"
  fi
}

# __IMOSH_FLAGS_TYPE_<flag name>=<flag type>
# __IMOSH_FLAGS_DESCRIPTION_<flag name>=<description>
# __IMOSH_FLAGS_ALIASES=(from:to ...)

imosh::internal::flag_type() {
  local name="$1"

  if [ "$#" -ne 1 ]; then
    LOG FATAL 'flag_type requires 1 arugument.'
  fi
  eval "func::print \"\${__IMOSH_FLAGS_TYPE_${name}}\""
}

imosh::internal::define_flag() {
  local type="$1"; shift

  local ARGS_alias='' ARGS_alias_flag=0 ARGS_group='main'
  eval "${IMOSH_PARSE_ARGUMENTS}"

  if [ "$#" -lt 3 ]; then
    LOG FATAL 'DEFINE_${type} requires 3+ arguments.'
  fi
  local name="$1"; shift
  local default_value="$1"; shift
  local description="$*"
  local group="${ARGS_group}"
  func::strtoupper group

  # Change the default value based on its corresponding environment variable.
  if func::isset "IMOSH_FLAGS_${name}"; then
    func::strcpy default_value "IMOSH_FLAGS_${name}"
  fi
  if ! imosh::internal::convert_type \
           "${type}" "${default_value}" >/dev/null; then
    LOG FATAL "${type}'s default value should be ${type}: ${default_value}"
  fi
  default_value="$(imosh::internal::convert_type "${type}" "${default_value}")"
  if func::isset "__IMOSH_FLAGS_TYPE_${name}"; then
    LOG FATAL "already defined flag: ${name}"
  fi
  func::strcpy "FLAGS_${name}" 'default_value'
  func::strcpy "__IMOSH_FLAGS_TYPE_${name}" 'type'
  if [ "${ARGS_alias}" != '' ]; then
    imosh::internal::define_flag "${type}" --alias_flag \
        "${ARGS_alias}" "${default_value}" "${description}"
    __IMOSH_FLAGS_ALIASES+=("${name}:${ARGS_alias}")
  fi
  if (( ! ARGS_alias_flag )); then
    local escaped_default_value=''
    case "${type}" in
      int) escaped_default_value="${default_value}";;
      bool)
        if (( default_value )); then
          escaped_default_value='true'
        else
          escaped_default_value='false'
        fi
        ;;
      *)
        escaped_default_value="${default_value}"
        func::escapeshellarg escaped_default_value
        ;;
    esac
    func::let "__IMOSH_FLAGS_DEFAULT_${name}" \
              "--${name}=${escaped_default_value}"
    if [ "${ARGS_alias}" != '' ]; then
      description+=" (Alias: --${ARGS_alias})"
    fi
    func::let "__IMOSH_FLAGS_DESCRIPTION_${name}" "${description}"
    __IMOSH_FLAGS+=("${group}:${name}")
  fi
}

DEFINE_string() { imosh::internal::define_flag string "$@"; }
DEFINE_int() { imosh::internal::define_flag int "$@"; }
DEFINE_bool() { imosh::internal::define_flag bool "$@"; }
DEFINE_double() { imosh::internal::define_flag double "$@"; }

imosh::internal::get_main_script() {
  local depth="${#BASH_SOURCE[@]}"
  local main_script="${BASH_SOURCE[$((depth-1))]}"
  echo "${main_script}"
}

imosh::internal::get_usage() {
  local file="${1}"
  while IFS='' read -r line; do
    case "${line}" in
      '#!'*) continue;;
      '# '*) echo "${line:2}";;
      '#'*)  echo "${line:1}";;
      *)     break;;
    esac
  done < "${file}" > "${__IMOSH_CORE_TMPDIR}/usage"
  if [ -s "${__IMOSH_CORE_TMPDIR}/usage" ]; then
    cat "${__IMOSH_CORE_TMPDIR}/usage"
  else
    echo 'No description.'
  fi
}

imosh::internal::flag_groups() {
  local groups=()
  local group=''
  local main_group_exists=0
  local imosh_group_exists=0
  for flag_name in "${__IMOSH_FLAGS[@]}"; do
    local parts=()
    func::explode parts ':' "${flag_name}"
    group="${parts[0]}"
    local lower_group="${group}"
    func::strtolower lower_group
    if [ "${lower_group}" == 'main' ]; then
      main_group_exists=1
    elif [ "${lower_group}" == 'imosh' ]; then
      imosh_group_exists=1
    else
      groups+=("${group}")
    fi
  done
  if (( main_group_exists )); then
    echo 'main'
  fi
  if [ "${#groups[@]}" -ne 0 -a "${FLAGS_helpfull}" -ne 0 ]; then
    func::array_unique groups
    for group in "${groups[@]}"; do
      echo "${group}"
    done
  fi
  if (( imosh_group_exists && FLAGS_helpfull )); then
    echo 'imosh'
  fi
}

imosh::internal::group_flags() {
  local group="$1"
  local lower_group="${group}"
  func::strtolower lower_group

  local flags=()
  for flag_name in "${__IMOSH_FLAGS[@]}"; do
    local parts=()
    func::explode parts ':' "${flag_name}"
    local lower_part="${parts[0]}"
    func::strtolower lower_part
    if [ "${lower_group}" != "${lower_part}" ]; then
      continue
    fi
    flags+=("${parts[1]}")
  done
  func::sort flags
  for flag in "${flags[@]}"; do
    echo "${flag}"
  done
}

imosh::internal::man() {
  echo ".TH ${0##*/} 1"; echo
  echo '.SH DESCRIPTION'
  __imosh::show_usage --format=groff --notitle \
      "$(imosh::internal::get_main_script)"

  echo '.SH OPTIONS'
  for flag_group in $(imosh::internal::flag_groups); do
    local upper_flag_group="${flag_group}"
    func::strtoupper upper_flag_group
    echo ".SS ${upper_flag_group} OPTIONS"
    for flag_name in $(imosh::internal::group_flags "${flag_group}"); do
      echo '.TP'
      echo -n '\fB'
      eval "echo -n \"\${__IMOSH_FLAGS_DEFAULT_${flag_name}}\""
      echo '\fP'
      eval "echo \"\${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\""
      echo
    done
  done
}

imosh::internal::help() {
  __imosh::show_usage --format=text --notitle \
      "$(imosh::internal::get_main_script)"
  echo "OPTIONS:"
  for flag_group in $(imosh::internal::flag_groups); do
    local upper_flag_group="${flag_group}"
    func::strtoupper upper_flag_group
    echo "  ${upper_flag_group} OPTIONS:"
    for flag_name in $(imosh::internal::group_flags "${flag_group}"); do
      eval "echo \"    \${__IMOSH_FLAGS_DEFAULT_${flag_name}}\""
      eval "echo \"\${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\"" | \
          fold -s -w 70 | while IFS= read -r line; do
        func::println "        ${line}"
      done
    done
  done
}

__imosh::help_markdown() {
  __imosh::show_usage --format=markdown --notitle \
      "$(imosh::internal::get_main_script)"
  echo "### Options"
  for flag_group in $(imosh::internal::flag_groups); do
    local upper_flag_group="${flag_group}"
    func::strtoupper upper_flag_group
    echo "#### ${flag_group} options"
    for flag_name in $(imosh::internal::group_flags "${flag_group}"); do
      eval "echo \"* \${__IMOSH_FLAGS_DEFAULT_${flag_name}}\""
      eval "echo \"    * \${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\""
    done
  done
}

__imosh::help() {
  case "${FLAGS_help_format}" in
    groff)
      imosh::internal::man;;
    markdown)
      __imosh::help_markdown;;
    *)
      imosh::internal::help;;
  esac
}

imosh::internal::init() {
  imosh::internal::parse_args flag "$@"
  if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
    eval "${IMOSH_ARGS[@]}"
  fi
  imosh::internal::init_log
  if [ "${#__IMOSH_FLAGS_ALIASES[@]}" -ne 0 ]; then
    for alias in "${__IMOSH_FLAGS_ALIASES[@]}"; do
      eval "FLAGS_${alias%%:*}=\"\${FLAGS_${alias#*:}}\""
      unset "FLAGS_${alias#*:}"
    done
  fi
  if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
    eval "${IMOSH_ARGS[@]}"
  fi
  if (( FLAGS_help || FLAGS_helpfull )) ||
     [ "${FLAGS_help_format}" != '' ]; then
    if [ "${FLAGS_help_format}" = '' ]; then
      if [ -t 1 ]; then
        FLAGS_help_format='groff'
      else
        FLAGS_help_format='text'
      fi
    fi
    if [ -t 1 -a "${FLAGS_help_format}" = 'groff' ]; then
      local man_file="${__IMOSH_CORE_TMPDIR}/man"
      __imosh::help >"${man_file}"
      man "${man_file}"
    else
      __imosh::help >&2
    fi
    exit 0
  fi
}

# Usage:
#   imosh::stack_trace [--skip_imosh] [message...]
#
# Shows a stack trace.  Arguments are used as a message.
imosh::stack_trace() {
  local ARGS_skip_imosh=0
  eval "${IMOSH_PARSE_ARGUMENTS}"

  local max_depth="${#BASH_LINENO[@]}"
  local i=0
  if [ "$*" = '' ]; then
    echo 'imosh::stack_trace is called' >&2
  else
    echo "$*" >&2
  fi
  while (( i < max_depth - 1 )); do
    if [ "${BASH_SOURCE[$((i+1))]}" != "${BASH_SOURCE[0]}" ]; then
      break
    fi
    (( i += 1 )) || true
  done
  while (( i < max_depth - 1 )); do
    local lineno="${BASH_LINENO[$((i))]}"
    local file="${BASH_SOURCE[$((i+1))]}"
    local function="${FUNCNAME[$((i+1))]}"
    echo "  at ${function} (${file}:${lineno})" >&2
    (( i += 1 )) || true
  done
}

imosh::internal::convert_type() {
  local type="$1"; shift
  local value="$1"; shift

  case "${type}" in
    int)
      if [[ "${value}" =~ ^-?[0-9]+$ ]]; then
        func::print "${value}"
      else
        return 1
      fi
      ;;
    string)
      func::print "${value}"
      ;;
    bool)
      case "${value}" in
        1|T|t|[Tt]rue) func::print 1;;
        0|F|f|[Ff]alse) func::print 0;;
        *) return 1;;
      esac
      ;;
    variant)
      func::print "${value}"
      ;;
    *) LOG FATAL "no such type: ${type}";;
  esac
}

__imosh::mktemp() {
  TMPDIR="${TMPDIR:-/tmp}"
  TMPDIR="${TMPDIR%/}"
  export TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/imosh.XXXXXX")"
  if [ "${TMPDIR}" = '' -o "${TMPDIR}" = '/' ]; then
    LOG FATAL 'failed to create a temporary directory.'
  fi

  export __IMOSH_CORE_TMPDIR="${TMPDIR}/.imosh"
  mkdir "${__IMOSH_CORE_TMPDIR}"
  local tmpdir="${TMPDIR}"
  func::escapeshellarg tmpdir
  func::atexit "rm -rf ${tmpdir}"

  # For backward compatibility.
  export IMOSH_TMPDIR="${TMPDIR}"
}

# __imosh::get_usage
#
# Usage:
#   void __imosh::get_usage(string file) > output
__imosh::get_usage() {
  local file="$1"
  local line=''
  while IFS= read -r line; do
    case "${line}" in
      '#!'*) continue;;
      '# '*) echo "${line:2}";;
      '#'*)  echo "${line:1}";;
      *)     break;;
    esac
  done < "${file}"
}

# __imosh::show_usage
#
# Usage:
#     bool __imosh::show_usage(string file) > output
#
# Options:
#   --format=text
#     Select one fromat from text/markdown/groff.
#   --title=true
#     Treat the first line as title.
#   --markdown_heading=#
#     Prepend a string to every heading.
__imosh::show_usage() {
  local ARGS_format=text ARGS_title=1 ARGS_markdown_heading='#'
  eval "${IMOSH_PARSE_ARGUMENTS}"

  if [ "$#" -eq 1 ]; then
    local file="$1"

    local usage="$(__imosh::get_usage "$1")"
    if [ "${usage}" = '' ]; then
      return
    fi

    local line='' first_line="${ARGS_title}" no_read=0
    while :; do
      if (( ! no_read )) && ! IFS= read -r line; then
        break
      fi
      no_read=0
      if [ "${ARGS_format}" = 'text' ]; then
        echo "${line}"
        continue
      fi
      func::rtrim line
      if (( first_line )); then
        case "${ARGS_format}" in
          groff)    echo ".TH ${line} 1";;
          markdown) echo "${ARGS_markdown_heading}# ${line}";;
        esac
        first_line=0
        continue
      fi
      while func::greg_match '*:' "${line}"; do
        local title="${line%:}"
        func::strtoupper title
        case "${ARGS_format}" in
          groff)    echo ".SH ${title}";;
          markdown) echo "${ARGS_markdown_heading}## ${line%:}";;
        esac
        local code_mode=0
        while IFS= read -r line; do
          if [ "${line:0:4}" != '    ' ]; then
            break
          fi
          if (( ! code_mode )); then
            case "${ARGS_format}" in
              groff)    echo '.Bd -literal -offset indent';;
              markdown) echo '```sh';;
            esac
            code_mode=1
          fi
          case "${ARGS_format}" in
            groff)    echo "${line#'    '}";;
            markdown) echo "${line#'    '}";;
          esac
        done
        if (( code_mode )); then
          case "${ARGS_format}" in
            groff)    echo '.Ed';;
            markdown) echo '```'
                      echo;;
          esac
        fi
      done
      if func::greg_match '*( )-*' "${line}"; then
        func::ltrim line
        if [ "${line:0:2}" = '- ' ]; then
          line="${line:2}"
        fi
        case "${ARGS_format}" in
          groff)    echo '.TP'
                    echo ".B ${line}";;
          markdown) echo "* ${line}";;
        esac
        local item_first_line=1
        while IFS= read -r line; do
          if func::greg_match '*( )-*' "${line}" || \
             func::greg_match '*([[:space:]])' "${line}"; then
            break
          fi
          func::ltrim line
          case "${ARGS_format}" in
            groff)    echo "${line}";;
            markdown)
              if (( item_first_line )); then
                echo "    * ${line}"
                item_first_line=0
              else
                echo "      ${line}"
              fi
              ;;
          esac
        done
        no_read=1
        continue
      fi
      echo "${line}"
    done <<<"${usage}"
    echo
  else
    LOG FATAL "Wrong number of arguments: $#"
  fi
}

ASSERT() {
  local last_state="${IMOSH_TEST_IS_FAILED}"
  IMOSH_TEST_IS_FAILED=0
  "$@"
  if (( IMOSH_TEST_IS_FAILED )); then
    exit 1
  fi
  IMOSH_TEST_IS_FAILED="${last_state}"
}

FAILURE() {
  IMOSH_TEST_IS_FAILED=1
  imosh::stack_trace --skip_imosh '*** Check failure ***'
}

EXPECT_TRUE() {
  if ! "$@"; then
    echo '  Actual: false' >&2
    echo 'Expected: true' >&2
    FAILURE
    return 1
  fi
  IFS=' ' eval 'LOG INFO "EXPECT_TRUE passes: $*"'
}

EXPECT_FALSE() {
  if "$@"; then
    echo '  Actual: true' >&2
    echo 'Expected: false' >&2
    FAILURE
    return 1
  fi
  IFS=' ' eval 'LOG INFO "EXPECT_FALSE passes: $*"'
}

ASSERT_TRUE() {
  ASSERT EXPECT_TRUE "$@"
}

ASSERT_FALSE() {
  ASSERT EXPECT_FALSE "$@"
}

# EXPECT_DEATH, EXPECT_ALIVE, ASSERT_DEATH, ASSERT_ALIVE
#
# Usage:
#   bool EXPECT_DEATH(string arguments...)
#   bool EXPECT_ALIVE(string arguments...)
#   void ASSERT_DEATH(string arguments...)
#   void ASSERT_ALIVE(string arguments...)
EXPECT_DEATH() {
  "$@" &
  if wait "$!"; then
    IFS=' ' eval 'LOG ERROR "Command did not die unexpectedly: $*"'
    return 1
  fi
  IFS=' ' eval 'LOG INFO "Command died as expected: $*"'
}

EXPECT_ALIVE() {
  "$@" &
  if ! wait "$!"; then
    IFS=' ' eval 'LOG ERROR "Command died unexpectedly: $*"'
    return 1
  fi
  IFS=' ' eval 'LOG INFO "Command did not die as expected: $*"'
}

ASSERT_DEATH() { ASSERT EXPECT_DEATH "$@"; }
ASSERT_ALIVE() { ASSERT EXPECT_ALIVE "$@"; }

# EXPECT_EQ, ASSERT_EQ -- Check if two values are equal.
#
# Usage:
#   bool EXPECT_EQ(string expected, string actual)
#   void ASSERT_EQ(string expected, string actual)
#
# Aliases:
#   EXPECT_STREQ is an alias of EXPECT_EQ, and ASSERT_STREQ is an alias of
#   ASSERT_EQ.
EXPECT_EQ() {
  if [ "$#" -ne 2 ]; then
    LOG ERROR 'EXPECT_EQ requires two arguments.'
    return 1
  fi
  if [ "$1" != "$2" ]; then
    echo "  Actual: $2" >&2
    echo "Expected: $1" >&2
    FAILURE
    return 1
  fi
  LOG INFO "EXPECT_EQ passes: '$1' == '$2'"
}

ASSERT_EQ() {
  ASSERT EXPECT_EQ "$@"
}

EXPECT_STREQ() { EXPECT_EQ "$@"; }
ASSERT_STREQ() { ASSERT_EQ "$@"; }

# EXPECT_NE, ASSERT_NE -- Check if two values are not equal.
#
# Usage:
#   bool EXPECT_NE(string expected, string actual)
#   void ASSERT_NE(string expected, string actual)
#
# Aliases:
#   EXPECT_STRNE is an alias of EXPECT_NE, and ASSERT_STRNE is an alias of
#   ASSERT_NE.
EXPECT_NE() {
  if [ "$#" -ne 2 ]; then
    LOG ERROR 'EXPECT_NE requires two arguments.'
    return 1
  fi
  if [ "$1" = "$2" ]; then
    echo "Actual: $2" >&2
    echo "Target: $1" >&2
    FAILURE
    return 1
  fi
  LOG INFO "EXPECT_NE passes: '$1' != '$2'"
}

ASSERT_NE() {
  ASSERT EXPECT_NE "$@"
}

EXPECT_STRNE() { EXPECT_NE "$@"; }
ASSERT_STRNE() { ASSERT_NE "$@"; }

# Return if imosh is reloaded.  Operations in 50+ run level may have
# destructive operations, so they are skipped in reloading.
if [ "${__IMOSH_IS_LOADED+loaded}" = 'loaded' ]; then
  return
fi

# Color definitions.  A shell script should restore terminal's original color
# using IMOSH_STYLE_DEFAULT when it changes color or style.

readonly IMOSH_STYLE_DEFAULT=$'\033[0m'
readonly IMOSH_COLOR_DEFAULT=$'\033[0;39m'
readonly IMOSH_COLOR_BLACK=$'\033[0;30m'
readonly IMOSH_COLOR_RED=$'\033[0;31m'
readonly IMOSH_COLOR_GREEN=$'\033[0;32m'
readonly IMOSH_COLOR_YELLOW=$'\033[0;33m'
readonly IMOSH_COLOR_BLUE=$'\033[0;34m'
readonly IMOSH_COLOR_MAGENTA=$'\033[0;35m'
readonly IMOSH_COLOR_CYAN=$'\033[0;36m'
readonly IMOSH_COLOR_WHITE=$'\033[0;37m'

readonly IMOSH_PARSE_ARGUMENTS='
    local IMOSH_ARGV IMOSH_ARGS
    imosh::internal::parse_args arg "$@"
    if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
      readonly "${IMOSH_ARGS[@]}"
    fi
    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
      set -- "${IMOSH_ARGV[@]}"
    fi'

readonly IMOSH_INIT='
    set -e -u
    imosh::internal::init "$@"
    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
      set -- "${IMOSH_ARGV[@]}"
    fi'

__IMOSH_FLAGS=()
__IMOSH_FLAGS_ALIASES=()

# Process ID that imosh initially runs on.
readonly IMOSH_ROOT_PID="$$"

# Variable not to output stack trace multiple times when exiting.
__IMOSH_STACK_TRACED=0

readonly UNAME="$(uname)"

__IMOSH_PROGRAM_NAME="${0##*/}"
__IMOSH_HOSTNAME="$(hostname -s)"
__IMOSH_USER="$(whoami)"
__IMOSH_LOG_PREFIX="${__IMOSH_PROGRAM_NAME}.${__IMOSH_HOSTNAME}.${__IMOSH_USER}"
__IMOSH_LOG_SUFFIX="$(date +'%Y%m%d.%H%M%S').$$"

imosh::internal::error_handler() {
  __IMOSH_STACK_TRACED=1
  imosh::stack_trace "error status: $?"
}

trap imosh::internal::error_handler ERR

imosh::internal::exit_handler() {
  local exit_code="$?"
  if (( exit_code && ! __IMOSH_STACK_TRACED )); then
    imosh::stack_trace "error status: ${exit_code}"
  fi

  local pid=''
  func::getmypid pid
  if [ "${pid}" != "${IMOSH_ROOT_PID}" ]; then
    LOG INFO 'finalizing a child process...'
    return
  fi

  LOG INFO 'finalizing...'

  set +e
  if [ -f "${__IMOSH_CORE_TMPDIR}/atexit.sh" ]; then
    source "${__IMOSH_CORE_TMPDIR}/atexit.sh"
  fi
  rm -rf "${__IMOSH_CORE_TMPDIR}"

  # Close log pipes and remove unused log files.
  exec 101>&- 102>&- 103>&- 104>&-
  local severity=''
  for severity in INFO WARNING ERROR FATAL; do
    local path="$(imosh::internal::log_file "${severity}")"
    if [ "${path}" != '' -a ! -s "${path}" ]; then
      rm "${path}"
    fi
  done
}

trap imosh::internal::exit_handler EXIT

imosh::internal::signal_handler() {
  local signal="$1"
  trap - "${signal}"
  local PID=''
  func::getmypid PID
  if [ "${PID}" == "${IMOSH_ROOT_PID}" ]; then
    LOG INFO 'killing child processes.'
    __imosh::kill "${IMOSH_ROOT_PID}"
    if [ -f "${__IMOSH_CORE_TMPDIR}/status" ]; then
      exit "$(cat "${__IMOSH_CORE_TMPDIR}/status")"
    fi
  fi
  LOG ERROR "$(imosh::stack_trace "terminated by signal: ${signal}" 2>&1)"
  kill -s "${signal}" "${PID}"
}

if ! shopt login_shell >/dev/null; then
  for signal in SIGHUP SIGINT SIGPIPE SIGTERM \
                SIGXCPU SIGXFSZ SIGUSR1 SIGUSR2; do
    trap "imosh::internal::signal_handler ${signal}" "${signal}"
  done
fi

# Close descriptors for logs beforehand for BASH3's bug.
exec 101>&- 102>&- 103>&- 104>&-
# Open descriptors for LOG without calling init_log.
exec 101>/dev/null 102>/dev/null 103>/dev/null 104>/dev/null

# Prepares a temporary directory and sets its path to TMPDIR.
__imosh::mktemp

DEFINE_bool --group=imosh --alias=h help false \
    'Print this help message and exit.'
DEFINE_bool --group=imosh helpfull false \
    'Print all the help message.'
DEFINE_bool --group=imosh 'alsologtostderr' false \
    'Log messages go to stderr in addition to logfiles.'
DEFINE_bool --group=imosh 'logtostderr' false \
    'Log messages go to stderr instead of logfiles.'
DEFINE_string --group=imosh 'log_dir' '' \
    'Directory to output log files.  Output no files if this flag is empty.'
DEFINE_string --group=imosh 'stacktrace_threshold' 'FATAL' \
    'Threshold to show stacktrace.'
DEFINE_string --group=imosh 'help_format' '' \
    'Help format to output.'

DEFINE_bool --group=imosh disown_php false 'Disown a PHP process.'

__IMOSH_IS_LOADED=1

LOG INFO 'imosh is ready.'

