#!/bin/bash
# print-flag-variables prints flag variables in imosh.

IMOSH_USE_DEFINE_FLAGS=1
source "$(dirname "${BASH_SOURCE}")"/../imosh || exit 1

sub::println '# This is automatically generated by print-flag-variables.'
declare | grep ^FLAGS
declare | grep ^__IMOSH_FLAGS
